services:
  - type: web
    name: solana-tracker-bot
    env: python
    buildCommand: ""
    startCommand: "python3 tracker_bot.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "8017958637:AAHGc7Zkw2B63GyR1nbnuckx3Hc8h4eelRY"
      - key: PASSWORD
        value: "Business2026$"
      - key: PORT
        value: "10000"
