services:
  - type: web
    name: solana-tracker-bot
    env: python
    buildCommand: ""
    startCommand: "python3 tracker_bot.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "TON_TOKEN_TELEGRAM_ICI"
      - key: PASSWORD
        value: "Business2026$"
      - key: PORT
        value: "10000"
