services:
  - type: web
    name: solana-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tracker_bot.py
    envVars:
      BOT_TOKEN:
        value: "8017958637:AAHGc7Zkw2B63GyR1nbnuckx3Hc8h4eelRY"
      PORT:
        value: "10000"
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
