services:
  - type: web
    name: solana-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tracker_bot.py
    envVars:
      BOT_TOKEN:
        value: "8104197353:AAEkh1gVe8eH9z48owFUc1KUENLVl7NG60k"
      PASSWORD:
        value: "Business2026$"
      PORT:
        value: "10000"
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
